"""add group role mapping to authentik settings

Revision ID: a63058d8be07
Revises: 5d2781f3293b
Create Date: 2026-10-05 14:48:16.849292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63058d8be07'
down_revision: Union[str, Sequence[str], None] = '5d2781f3293b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentik_settings', sa.Column('admin_group', sa.String(length=255), server_default='household-system-admins', nullable=False))
    op.add_column('authentik_settings', sa.Column('user_group', sa.String(length=255), server_default='household-system-users', nullable=False))
    op.add_column('authentik_settings', sa.Column('viewer_group', sa.String(length=255), server_default='household-system-viewers', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authentik_settings', 'viewer_group')
    op.drop_column('authentik_settings', 'user_group')
    op.drop_column('authentik_settings', 'admin_group')
    # ### end Alembic commands ###
