"""add authentik settings

Revision ID: 5d2781f3293b
Revises: 5a06b47bd947
Create Date: 2026-10-03 19:07:14.856941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2781f3293b'
down_revision: Union[str, Sequence[str], None] = '5a06b47bd947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentik_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=False),
    sa.Column('jwks_url', sa.String(length=512), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('authorize_url', sa.String(length=512), nullable=False),
    sa.Column('token_url', sa.String(length=512), nullable=False),
    sa.Column('end_session_url', sa.String(length=512), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authentik_settings')
    # ### end Alembic commands ###
