"""add reports, push subscriptions, eur conversion rate

Revision ID: e3e5d7c393ec
Revises: 79d3133adc70
Create Date: 2026-10-02 18:37:17.946611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e5d7c393ec'
down_revision: Union[str, Sequence[str], None] = '79d3133adc70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_user_id'], ['household_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.Enum('week', 'month', name='report_period'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['household_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('household_settings', sa.Column('points_to_eur_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('household_settings', 'points_to_eur_rate')
    op.drop_table('reports')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###

    # Postgres native ENUM types aren't owned by the table that uses them,
    # so dropping 'reports' above does NOT drop 'report_period' — without
    # this, re-running upgrade after a downgrade fails with "type already
    # exists".
    sa.Enum(name="report_period").drop(op.get_bind(), checkfirst=True)
