"""add task reassignment tracking and daily balance stamp

Revision ID: 29393a74fdb2
Revises: 6b7390f3fea3
Create Date: 2026-10-03 01:36:43.764619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29393a74fdb2'
down_revision: Union[str, Sequence[str], None] = '6b7390f3fea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('household_settings', sa.Column('last_balance_run', sa.Date(), nullable=True))
    op.drop_column('household_settings', 'last_balance_week')
    op.drop_column('household_settings', 'last_balance_month')
    op.add_column('task_assignments', sa.Column('reassigned_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_assignments', 'reassigned_at')
    op.add_column('household_settings', sa.Column('last_balance_month', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('household_settings', sa.Column('last_balance_week', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('household_settings', 'last_balance_run')
    # ### end Alembic commands ###
