"""add week start, auto reports, paid tracking, cached role

Revision ID: 6ee384f7ff1a
Revises: 29393a74fdb2
Create Date: 2026-10-03 13:47:56.805798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee384f7ff1a'
down_revision: Union[str, Sequence[str], None] = '29393a74fdb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('household_settings', sa.Column('week_start_weekday', sa.Integer(), server_default='0', nullable=False))
    op.add_column('household_settings', sa.Column('auto_report_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('household_settings', sa.Column('last_auto_report_period', sa.Date(), nullable=True))
    op.add_column('household_users', sa.Column('role', sa.String(length=20), nullable=True))
    op.add_column('reports', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('reports', 'generated_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'generated_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reports', 'paid_at')
    op.drop_column('household_users', 'role')
    op.drop_column('household_settings', 'last_auto_report_period')
    op.drop_column('household_settings', 'auto_report_enabled')
    op.drop_column('household_settings', 'week_start_weekday')
    # ### end Alembic commands ###
