"""event group schedule and nullable todo creator

Revision ID: 0b83dc22261d
Revises: 8a15cc89a2f2
Create Date: 2026-10-06 01:13:41.884150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b83dc22261d'
down_revision: Union[str, Sequence[str], None] = '8a15cc89a2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_groups', sa.Column('schedule_recurrence', sa.String(length=10), nullable=True))
    op.add_column('event_groups', sa.Column('schedule_weekdays', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('event_groups', sa.Column('schedule_hour', sa.Integer(), server_default='18', nullable=False))
    op.alter_column('todo_items', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: this fails once any row exists with created_by_id NULL — i.e.
    # once a scheduled Event Group has auto-triggered at least once (see
    # crud.run_scheduled_event_groups_if_due). There's no good automatic
    # backfill value (no real user "created" those rows), so a downgrade
    # past this point needs those rows handled by hand first.
    op.alter_column('todo_items', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('event_groups', 'schedule_hour')
    op.drop_column('event_groups', 'schedule_weekdays')
    op.drop_column('event_groups', 'schedule_recurrence')
    # ### end Alembic commands ###
