"""add preferred_language and default_language

Revision ID: 59982065edd0
Revises: 7a2baea5f6dc
Create Date: 2026-10-06 18:53:05.163032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59982065edd0'
down_revision: Union[str, Sequence[str], None] = '7a2baea5f6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('household_settings', sa.Column('default_language', sa.String(length=5), server_default='en', nullable=False))
    op.add_column('household_users', sa.Column('preferred_language', sa.String(length=5), server_default='en', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('household_users', 'preferred_language')
    op.drop_column('household_settings', 'default_language')
    # ### end Alembic commands ###
