"""add cancelled_at to todo items

Revision ID: 9c1717a8eafd
Revises: a74f9c9fa5ed
Create Date: 2026-10-10 19:51:24.479737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1717a8eafd'
down_revision: Union[str, Sequence[str], None] = 'a74f9c9fa5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_items', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_items', 'cancelled_at')
    # ### end Alembic commands ###
