"""add weekly nudge schedule settings

Revision ID: 303737a446b6
Revises: e3e5d7c393ec
Create Date: 2026-10-02 19:06:39.963082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303737a446b6'
down_revision: Union[str, Sequence[str], None] = 'e3e5d7c393ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('household_settings', sa.Column('nudge_weekday', sa.Integer(), nullable=True))
    # server_default so this doesn't fail against the existing settings row
    # (NOT NULL column added to a non-empty table — see MIGRATIONS.md).
    op.add_column('household_settings', sa.Column('nudge_hour', sa.Integer(), nullable=False, server_default='18'))
    op.add_column('household_settings', sa.Column('last_nudge_sent_week', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('household_settings', 'last_nudge_sent_week')
    op.drop_column('household_settings', 'nudge_hour')
    op.drop_column('household_settings', 'nudge_weekday')
    # ### end Alembic commands ###
