"""add chores and points domain

Revision ID: 79d3133adc70
Revises: 
Create Date: 2026-10-02 17:25:20.268525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d3133adc70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('household_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_points_goal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('on_break', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_users_subject'), 'household_users', ['subject'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('weekdays', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('times_per_day', sa.Integer(), nullable=False),
    sa.Column('ramp_up_enabled', sa.Boolean(), nullable=False),
    sa.Column('ramp_up_bonus_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_categories',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'category_id')
    )
    op.create_table('todo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'completed', 'cancelled', name='todo_status'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['household_users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['household_users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['household_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('task', 'todo', name='points_source'), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('todo_item_id', sa.Integer(), nullable=True),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_user_id'], ['household_users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['todo_item_id'], ['todo_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('todo_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points_entries')
    op.drop_table('todo_items')
    op.drop_table('task_categories')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_household_users_subject'), table_name='household_users')
    op.drop_table('household_users')
    op.drop_table('household_settings')
    op.drop_table('categories')
    # ### end Alembic commands ###

    # Postgres native ENUM types aren't owned by the table that uses them,
    # so dropping the tables above does NOT drop these — without this,
    # re-running upgrade after a downgrade fails with "type already exists".
    sa.Enum(name="points_source").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="todo_status").drop(op.get_bind(), checkfirst=True)
