"""add chained tasks

Revision ID: 66d5a117a235
Revises: 6ee384f7ff1a
Create Date: 2026-10-05 17:19:46.683032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d5a117a235'
down_revision: Union[str, Sequence[str], None] = '6ee384f7ff1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_chain_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=False),
    sa.Column('child_task_id', sa.Integer(), nullable=False),
    sa.Column('same_user', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_task_id', 'child_task_id', name='uq_chain_link_parent_child')
    )
    op.add_column('todo_items', sa.Column('chain_link_id', sa.Integer(), nullable=True))
    op.add_column('todo_items', sa.Column('spawned_by_entry_id', sa.Integer(), nullable=True))
    op.add_column('todo_items', sa.Column('exclude_user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_todo_chain_spawn', 'todo_items', ['chain_link_id', 'spawned_by_entry_id'])
    op.create_foreign_key('fk_todo_items_chain_link_id', 'todo_items', 'task_chain_links', ['chain_link_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_todo_items_exclude_user_id', 'todo_items', 'household_users', ['exclude_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_todo_items_spawned_by_entry_id', 'todo_items', 'points_entries', ['spawned_by_entry_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_todo_items_spawned_by_entry_id', 'todo_items', type_='foreignkey')
    op.drop_constraint('fk_todo_items_exclude_user_id', 'todo_items', type_='foreignkey')
    op.drop_constraint('fk_todo_items_chain_link_id', 'todo_items', type_='foreignkey')
    op.drop_constraint('uq_todo_chain_spawn', 'todo_items', type_='unique')
    op.drop_column('todo_items', 'exclude_user_id')
    op.drop_column('todo_items', 'spawned_by_entry_id')
    op.drop_column('todo_items', 'chain_link_id')
    op.drop_table('task_chain_links')
    # ### end Alembic commands ###
