"""overdue cleanup setting

Revision ID: e8639b5f66da
Revises: 91f748ff9d57
Create Date: 2026-10-06 12:16:18.274262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8639b5f66da'
down_revision: Union[str, Sequence[str], None] = '91f748ff9d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('household_settings', sa.Column('overdue_delete_after_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('household_settings', 'overdue_delete_after_days')
    # ### end Alembic commands ###
