"""household timezone setting

Revision ID: 7a2baea5f6dc
Revises: e8639b5f66da
Create Date: 2026-10-06 13:55:07.029766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2baea5f6dc'
down_revision: Union[str, Sequence[str], None] = 'e8639b5f66da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('household_settings', sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('household_settings', 'timezone')
    # ### end Alembic commands ###
