"""chain tasks spawn at parent creation

Revision ID: 91f748ff9d57
Revises: 0b83dc22261d
Create Date: 2026-10-06 11:24:06.761436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f748ff9d57'
down_revision: Union[str, Sequence[str], None] = '0b83dc22261d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_items', sa.Column('spawned_by_todo_id', sa.Integer(), nullable=True))
    op.add_column('todo_items', sa.Column('chain_spawn_handled', sa.Boolean(), server_default='false', nullable=False))
    op.create_unique_constraint('uq_todo_chain_spawn_by_todo', 'todo_items', ['chain_link_id', 'spawned_by_todo_id'])
    op.create_foreign_key('fk_todo_items_spawned_by_todo_id', 'todo_items', 'todo_items', ['spawned_by_todo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_todo_items_spawned_by_todo_id', 'todo_items', type_='foreignkey')
    op.drop_constraint('uq_todo_chain_spawn_by_todo', 'todo_items', type_='unique')
    op.drop_column('todo_items', 'chain_spawn_handled')
    op.drop_column('todo_items', 'spawned_by_todo_id')
    # ### end Alembic commands ###
