"""add profile photo to household users

Revision ID: 57fad95d109c
Revises: 9543afb3ca18
Create Date: 2026-10-02 19:39:06.117179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57fad95d109c'
down_revision: Union[str, Sequence[str], None] = '9543afb3ca18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('household_users', sa.Column('image_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('household_users', 'image_path')
    # ### end Alembic commands ###
