"""add task recurrence and assignments

Revision ID: 6b7390f3fea3
Revises: 57fad95d109c
Create Date: 2026-10-03 01:02:47.337868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7390f3fea3'
down_revision: Union[str, Sequence[str], None] = '57fad95d109c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('household_user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_user_id'], ['household_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'period_start', name='uq_task_assignment_period')
    )
    op.add_column('household_settings', sa.Column('last_balance_week', sa.String(length=10), nullable=True))
    op.add_column('household_settings', sa.Column('last_balance_month', sa.String(length=7), nullable=True))
    # Unlike op.create_table, op.add_column doesn't create a brand-new
    # enum type for you — it has to exist before the ALTER TABLE runs.
    task_recurrence = sa.Enum('daily', 'weekly', 'monthly', name='task_recurrence')
    task_recurrence.create(op.get_bind(), checkfirst=True)
    op.add_column('tasks', sa.Column('recurrence', task_recurrence, server_default='daily', nullable=False))
    # ### end Alembic commands ###

    # Backfill: every existing row just landed as 'daily' via the server
    # default above. A task that actually has specific weekdays set (and
    # isn't scheduled on all 7, which is equivalent to daily) was created
    # through the "only on specific weekdays" picker — that's `weekly`,
    # not `daily`. There's no pre-existing way to express `monthly`, so no
    # row backfills to that.
    op.execute(
        """
        UPDATE tasks
        SET recurrence = 'weekly'
        WHERE weekdays IS NOT NULL AND array_length(weekdays, 1) < 7
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurrence')
    op.drop_column('household_settings', 'last_balance_month')
    op.drop_column('household_settings', 'last_balance_week')
    op.drop_table('task_assignments')
    # ### end Alembic commands ###
    # Dropping the column doesn't drop the enum type itself.
    sa.Enum(name='task_recurrence').drop(op.get_bind(), checkfirst=True)
