"""add created_by_id to tasks

Revision ID: 469033d6a38b
Revises: 9c1717a8eafd
Create Date: 2026-10-11 00:44:56.594488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469033d6a38b'
down_revision: Union[str, Sequence[str], None] = '9c1717a8eafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tasks_created_by_id_household_users', 'tasks', 'household_users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_created_by_id_household_users', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'created_by_id')
    # ### end Alembic commands ###
