"""add pinned_user_id to tasks

Revision ID: 141c12efdcbb
Revises: 59982065edd0
Create Date: 2026-10-09 23:35:47.197970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141c12efdcbb'
down_revision: Union[str, Sequence[str], None] = '59982065edd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('pinned_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tasks_pinned_user_id_household_users', 'tasks', 'household_users', ['pinned_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tasks_pinned_user_id_household_users', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'pinned_user_id')
    # ### end Alembic commands ###
