"""add event groups

Revision ID: 8a15cc89a2f2
Revises: 59de15c9ab1e
Create Date: 2026-10-06 00:23:05.129855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a15cc89a2f2'
down_revision: Union[str, Sequence[str], None] = '59de15c9ab1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event_group_exclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_group_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_group_id'], ['event_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_group_id', 'task_id', name='uq_event_group_exclusion')
    )
    op.create_table('event_group_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_group_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_group_id'], ['event_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['household_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_group_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_group_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_group_id'], ['event_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_group_id', 'task_id', name='uq_event_group_task')
    )
    op.add_column('todo_items', sa.Column('source_task_id', sa.Integer(), nullable=True))
    op.add_column('todo_items', sa.Column('event_group_run_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_todo_items_event_group_run_id', 'todo_items', 'event_group_runs', ['event_group_run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_todo_items_source_task_id', 'todo_items', 'tasks', ['source_task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_todo_items_event_group_run_id', 'todo_items', type_='foreignkey')
    op.drop_constraint('fk_todo_items_source_task_id', 'todo_items', type_='foreignkey')
    op.drop_column('todo_items', 'event_group_run_id')
    op.drop_column('todo_items', 'source_task_id')
    op.drop_table('event_group_tasks')
    op.drop_table('event_group_runs')
    op.drop_table('event_group_exclusions')
    op.drop_table('event_groups')
    # ### end Alembic commands ###
