"""add takeover requests

Revision ID: b413837c5c6f
Revises: 66d5a117a235
Create Date: 2026-10-05 18:36:03.197942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b413837c5c6f'
down_revision: Union[str, Sequence[str], None] = '66d5a117a235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('takeover_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('todo_item_id', sa.Integer(), nullable=True),
    sa.Column('task_assignment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'cancelled', name='takeover_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(todo_item_id IS NOT NULL) != (task_assignment_id IS NOT NULL)', name='ck_takeover_exactly_one_item'),
    sa.ForeignKeyConstraint(['requester_id'], ['household_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['household_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_assignment_id'], ['task_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['todo_item_id'], ['todo_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_takeover_pending_assignment', 'takeover_requests', ['task_assignment_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('uq_takeover_pending_todo', 'takeover_requests', ['todo_item_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_takeover_pending_todo', table_name='takeover_requests', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('uq_takeover_pending_assignment', table_name='takeover_requests', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('takeover_requests')
    # ### end Alembic commands ###
    # Dropping the table doesn't drop its enum type — without this, a
    # re-run of upgrade() after this downgrade fails with "type
    # takeover_status already exists" (see MIGRATIONS.md).
    sa.Enum(name='takeover_status').drop(op.get_bind(), checkfirst=True)
